# Default values for RKM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/dmlabs/rkm
  tag: v0.0.1
  pullPolicy: IfNotPresent

clusterInformation:
  # Kubernetes cluster information for RKM to collect the correct metrics
  clusterName: kubernetes-cluster-1
  kubeAPIServerPort: 6443
  tz: Europe/Zurich

rkmOutpost:
  schedule: "* * * * *"

rkmMissionControl:
  # InfluxDB URL and InfluxDB Name of the RKM mission control
  # NOTE: This chart expects InfluxDB with authentication and you need to create a Kubernetes secret with that information
  # -> kubectl create secret generic rkm-secrets --from-literal=INFLUXDB_USER=<user> --from-literal=INFLUXDB_PW=<password> -n <rkm-namespace>
  influxDBUrl: http://influxdb.apps.dmlabs.ch
  influxDBPort: 80
  influxDBName: rkm